name: PowerElytra
version: 1.1
description: Power Elytra Minecraft 1.9
authors: [DimoN, angal, JekaRUS]
website: http://playcraft.com.ua/

main: elytra.Elytra

commands:
    elytra:
        aliases: [powerelytra,pe,уднекф]
        
permissions:
    powerelytra.player.use:
        description: Can use PowerElitra
        default: true
    powerelytra.player.fuel:
        description: Can use Fuel
        default: true
    powerelytra.admin.nofuel:
        description: Not need fuel
        default: op
    powerelytra.admin.givefuel:
        description: Not need fuel
        default: op
    powerelytra.admin.reload:
        description: Can use command reload
        default: op